export const dummyContacts = [
  {
    id: "1",
    name: "Alice Johnson",
    email: "alice.johnson@example.com",
    isOnline: true,
  },
  {
    id: "2",
    name: "Brian Smith",
    email: "brian.smith@example.com",
    isOnline: false,
  },
  {
    id: "3",
    name: "Carla Brown",
    email: "carla.brown@example.com",
    isOnline: true,
  },
  {
    id: "4",
    name: "David Lee",
    email: "david.lee@example.com",
    isOnline: true,
  },
  {
    id: "5",
    name: "Eva Adams",
    email: "eva.adams@example.com",
    isOnline: false,
  },
  {
    id: "6",
    name: "Frank Miller",
    email: "frank.miller@example.com",
    isOnline: false,
  },
  {
    id: "7",
    name: "Grace Turner",
    email: "grace.turner@example.com",
    isOnline: true,
  },
  {
    id: "8",
    name: "Harry Walker",
    email: "harry.walker@example.com",
    isOnline: true,
  },
  {
    id: "9",
    name: "Ivy Green",
    email: "ivy.green@example.com",
    isOnline: false,
  },
  {
    id: "10",
    name: "Jack White",
    email: "jack.white@example.com",
    isOnline: false,
  },
  {
    id: "11",
    name: "Kathy Scott",
    email: "kathy.scott@example.com",
    isOnline: true,
  },
  {
    id: "12",
    name: "Liam Young",
    email: "liam.young@example.com",
    isOnline: false,
  },
  {
    id: "13",
    name: "Mona Bell",
    email: "mona.bell@example.com",
    isOnline: true,
  },
  {
    id: "14",
    name: "Nate Harris",
    email: "nate.harris@example.com",
    isOnline: true,
  },
  {
    id: "15",
    name: "Olivia Clark",
    email: "olivia.clark@example.com",
    isOnline: false,
  },
  {
    id: "16",
    name: "Paul King",
    email: "paul.king@example.com",
    isOnline: true,
  },
  {
    id: "17",
    name: "Quinn Reed",
    email: "quinn.reed@example.com",
    isOnline: false,
  },
  {
    id: "18",
    name: "Rachel Cox",
    email: "rachel.cox@example.com",
    isOnline: true,
  },
  {
    id: "19",
    name: "Steve Wright",
    email: "steve.wright@example.com",
    isOnline: false,
  },
  {
    id: "20",
    name: "Tina Moore",
    email: "tina.moore@example.com",
    isOnline: true,
  },
  {
    id: "21",
    name: "Uma Stone",
    email: "uma.stone@example.com",
    isOnline: false,
  },
  {
    id: "22",
    name: "Victor Lane",
    email: "victor.lane@example.com",
    isOnline: true,
  },
  {
    id: "23",
    name: "Wendy Knight",
    email: "wendy.knight@example.com",
    isOnline: false,
  },
  {
    id: "24",
    name: "Xander Ross",
    email: "xander.ross@example.com",
    isOnline: true,
  },
  {
    id: "25",
    name: "Yara Dean",
    email: "yara.dean@example.com",
    isOnline: false,
  },
  {
    id: "26",
    name: "Zane Porter",
    email: "zane.porter@example.com",
    isOnline: true,
  },
];
